novari:
    flyt:
        web-instance-gateway:
            kafka:
                topic:
                    instance-receival-error:
                        retention-time: "4d"
                        cleanup-frequency: NORMAL
                        partitions: 1
