server:
    tomcat:
        max-swallow-size: 100MB

novari:
    flyt:
        web-instance-gateway:
            max-request-size: 100MB
            kafka:
                topic:
                    instance-receival-error:
                        retention-time: "4d"
                        cleanup-frequency: NORMAL
                        partitions: 1
